Added ability to reference specification revisions to merge_checklists. Fixed checklist and outline parsing errors discovered as part of the merge_checklists development. Enhanced check_all* scripts to output pass/fail indication, and an identifier for what just passed/failed. Added more up to date XML file for Rev 2.2 stack, and PDF for rev 3.2. Remove old format translation files.

diff --git a/check_all_checklists b/check_all_checklists
--- a/check_all_checklists
+++ b/check_all_checklists
@@ -1,6 +1,24 @@
 #!/bin/bash
+function check_rc(){
+        rc=$?
+        echo ---------------------------------------
+        if [[ $rc != 0 ]];
+        then
+                echo $1 ' FAILURE!'
+                exit $rc
+        else
+                echo $1 ' SUCCESS!'
+        fi
+        echo ---------------------------------------
+}
+
 ./parse_checklist.py -f Historic_Checklists/Error\ Management\ Checklist.xml -r 1.3 > Historic_Checklists/ErrorManagementChecklist.txt
+check_rc 'Parse ErrorManagementChecklist'
 ./parse_checklist.py -f Historic_Checklists/Data\ Streaming\ Checklist.xml -r 1.3 > Historic_Checklists/DataStreamingChecklist.txt
+check_rc 'Parse DataStreamingChecklist'
 ./parse_checklist.py -f Historic_Checklists/rev1_3_rio_chklst.xml -r 1.3 > Historic_Checklists/rev1_3_rio_chklist.txt
-./parse_checklist.py -f Historic_Checklists/rapidio_interop_checklist_rev2_2.xml -r 2.2 -p 6 -t > Historic_Checklists/rev2_2_rio_chklist.txt
-./merge_checklists.py -f Historic_Checklists/ErrorManagementChecklist.txt -f Historic_Checklists/DataStreamingChecklist.txt -f Historic_Checklists/rev1_3_rio_chklist.txt -f Historic_Checklists/rev2_2_rio_chklist.txt > Historic_Checklists/merged_sorted_checklist.txt
+check_rc 'Parse Rev1.3'
+./parse_checklist.py -f Historic_Checklists/rapidio_interop_checklist_rev2_2.xml -r 2.2 -p 6 -t > Historic_Checklists/rapidio_interop_checklist_rev2_2.txt
+check_rc 'Parse Rev2.2Part6'
+./merge_checklists.py -c Historic_Checklists/ErrorManagementChecklist.txt -c Historic_Checklists/DataStreamingChecklist.txt -c Historic_Checklists/rev1_3_rio_chklist.txt -c Historic_Checklists/rapidio_interop_checklist_rev2_2.txt -o Standards/outline_1.3.txt  -o Standards/outline_2.2.txt  > Historic_Checklists/merged_sorted_checklist.txt
+check_rc 'MERGE all checklists'
